baseURL = "http://gopher.zone/"
canonifyurls = true
languageCode = "en-us"
publishDir = "docs"
theme = "blank"
title = "Highway to the Gopher Zone"

pygmentsstyle       = "bw"
pygmentsCodeFences = true

[params]
  sitename = "Highway to the Gopher Zone"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "https://github.com/jamestomasino/gopher.zone/blob/master/README.md"

[author]
    name = "James Tomasino"

[permalinks]
  post = "/:title/"
